* oysolscript
** 소개
이맥스에서 [[https://ko.wikipedia.org/wiki/%EC%98%88%EC%9D%BC_%EB%A1%9C%EB%A7%88%EC%9E%90_%ED%91%9C%EA%B8%B0%EB%B2%95][예일 로마자 표기법]]으로 작성한 글을 [[https://github.com/Tzetachi/Computer-Modern-Unicode-Oesol][Computer Modern Unicode Oesol(이하, CMUO)]] 글꼴에 대응하도록 바꿔주는 oysolscript입니다. oysolscript는 [[https://bitbucket.org/novadh/oesolscript/src/master/][oesolscript]]에서 영감을 얻어서 시작되었습니다. [[https://bitbucket.org/novadh/][de Hi Nova]]님께 감사드립니다.
** 왜 예일 로마자 표기법인가?
*** 전사하기 쉽습니다.
현행 로마자 표기법은 발음을 중시하여 초성으로 오느냐 종성으로 오느냐를 고려해서 하나의 한글 자모에 여러 개의 로마자를 배정하기 때문에 외우는 것도 자체도 어렵고, 전자법을 쓸 때는 어떤 것을 사용해야 하는지를 또 외워야 합니다. 국립국어원에서 어떤 것을 사용해야 하는지 정해주긴 하였지만 저는 일단 그것부터가 마음에 들지 않습니다. 예일 로마자 표기법은 일대일대응이어서 그냥 마음이 편합니다.
*** 입력하기 쉽습니다.
매큔-라이샤워 표기법은 일단 ŏ, ŭ 이렇게 생긴 문자도 써야 하고 '도 찍어줘야 하고 유성음인지 무성음인지도 구별해야 하는데, 한국인 화자에게는 별로 중요한 문제가 아니죠. 다 비슷하게 들리니까요. 외국인한테는 최대한 비슷하게 발음을 구현하는 게 중요하겠죠. 하지만 저희는 로마자는 거쳐 가는 통로이고 결국 CMUO로 바꿀 것이지 않습니까? 경제성을 따져보아야 하고, 한국어 화자에게 가장 사용하기 적합한 방식이 예일 로마자 표기법이라고 생각합니다.
*** 외우기 쉽습니다.
국어의 음운론 공부를 해보신 분들은 별로 외울 것이 없습니다. 왜냐하면 이치를 담았기 때문입니다. 예를 들어서 ㅋ, ㅌ, ㅍ, ㅊ에는 ㄱ, ㄷ, ㅂ, ㅈ에 유기음이 추가된 것입니다. 유기음은 국제 음성 기호로 ʰ로 표기합니다. 따라서 kh, th, ph, ch인 것이 자연스럽습니다. ㄱ, ㄷ, ㅂ은 받아들이시기 쉬우실 거 같은데 아마도 ㅈ이 c인 것은 좀 아니다 싶으실 수도 있지만 ㅊ이 ch이니 유기음이 빠졌으므로 c가 되는 것이고 전체적으로 일관성이 있습니다. 모음 부분도 마찬가지인데 y와 w를 적소에 사용하는 아름다운 모습을 보입니다.
*** 현행 로마자 표기법을 이용할 경우의 예상되는 어려움
**** 국어의 표준 로마자 표기법의 수명
몇십 년 뒤에도 표준 로마자 표기법이 그대로일 것이라는 확신이 없습니다. 1948년, 1959년, 2000년, 2014년. 공식 로마자 표기법이 바뀐 연도를 나열한 것입니다. 공식 로마자 표기법이 은근히 자주 바뀌는 것을 알 수 있습니다. 비공식 표기법까지 나열하면 1895년, 1937년, 1942년, 1948년, 1959년, 2000년, 2014년에 로마자 표기법이 새로 고안되었습니다. 이 정도 추세라면 100년 안에 두어 번쯤 개정되어도 전혀 이상한 것이 없습니다. 이 중에서 예일 로마자 표기법은 1942년에 발표된 것으로 역사와 전통을 가지고 있다고 해도 과언이 아닐 것입니다.
**** 전자법의 사용
발음을 중시하는 지금의 로마자 표기법을 이용하면 전자법을 사용해야 하므로 역설적인 면이 있습니다. 전자법을 사용하게 되면 한국인이 생각하기에 발음이 유사하게 느껴진다는 유일무이한 장점을 저버리는 셈입니다.
**** ng 처리의 문제
ng이 ㅇ인지 ㄴㄱ인지 알기 어렵습니다. 전자법에서 ㄱ을 g로 표현하기 때문에 생긴 문제입니다. 그리고 이 경우 n-g 이런 식으로 쓰게 되면 현행 로마자 표기법에서 이미 붙임표를 초성 ㅇ을 구별하는 곳에 사용하고 있으므로 그것과 충돌합니다. 그리고 최현배 선생께서는 줄표와 붙임표를 구별하여 사용하셨고, 이는 최현배 선생의 여러 저서에서 확인할 수 있어서, 줄표도 함부로 사용할 수가 없습니다. 이 모든 문제 원인이 현행 로마자 표기법은 발음 중심인데, 이것을 전자법으로 사용하게 되면서 생기는 문제라고 생각합니다. 그냥 예일 로마자 표기법을 사용하면 다 해결되는 문제입니다. 참고로 최현배 선생께서는 ㄱ에는 k, ㄷ에는 t, ㅂ에는 p를 써야 한다고 주창한 바가 있으시며 저 또한 전적으로 동의합니다. 
** 설치 방법
oysolscript.el 파일을 적절한 위치에 두고, Emacs 초기 실행 파일(Linux의 경우 ~/.emacs에 위치함)에 아래의 코드를 적절히 상황에 맞게끔 수정하여 추가합니다.
#+BEGIN_SRC emacs-lisp
  (load "파일이/있는/경로를/입력하세요/oysolscript.el")
#+END_SRC
** 단축키
Yale의 머리글자를 따서 C-x y를 누르면 oysolscript가 실행되도록 설정했습니다.
** 유의 사항
oya는 ㅗㅑ일까요? ㅚㅏ일까요? 사실 이런 문제가 한두 군데에서 발생하는 문제가 아닙니다. 그래서 이 모든 것들을 논리적으로 해결하려면 이것을 구별하는 기호가 필요할 수밖에 없지만 저는 그렇게 할 생각이 없습니다. 구별하는 기호를 도입하게 되면, 그 기호를 치고 싶으면 또 그 기호를 다른 방식으로 표현해야 합니다. 그냥 이런 문제점을 안고 가기로 하였습니다. 대신에 그러한 문제점이 보일 때마다 oysolscript를 실행해주세요. 기본 단축키는 C-x y이지만 단축키가 간결할수록 자주 실행하기가 편하겠지요?
** 개선 예정
다른 로마자 기반 언어가 섞여 있으면 사용하기 어려운 문제가 있으므로, 현재 문단으로 범위를 한정하거나, 선택된 부분이 있으면 그 영역으로 한정하거나 하는 방식을 추가할 것입니다.
** 참고 문서
http://xahlee.info/emacs/emacs/elisp_find_replace_text.html
